### PR TITLE
Update ci-hpc-config.yml with OMPI_MCA_rmaps_base_oversubscribe=1

### PR DESCRIPTION
**Pull request by geier1993**
Let's see if this helps...

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf/multio?pullRequest=25) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf/multio?pullRequest=25) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf/multio?pullRequest=25) it.</sub>

**Comment by geier1993** [comment]
Running the workflow multiple times. So far it succeeded

**Comment by geier1993** [comment]
Passed 2 times without problems

**Comment by geier1993** [comment]
Notification works as expected now

**Review by dsarmany — APPROVED** [review]

**Pull request merged**
